[package]
name = "lru"
edition = "2021"
version = "0.7.2"
authors = ["Jerome Froelich <jeromefroelic@hotmail.com>"]
description = "A LRU cache implementation"
homepage = "https://github.com/jeromefroe/lru-rs"
repository = "https://github.com/jeromefroe/lru-rs.git"
documentation = "https://docs.rs/lru/"
readme = "README.md"
license = "MIT"
keywords = ["LRU", "cache"]

[features]
default = ["hashbrown"]
nightly = ["hashbrown", "hashbrown/nightly"]

[dependencies]
hashbrown = { version = "0.11.2", optional = true }
dashmap = "5.0.0"
ahash = "0.7.6"

[dev-dependencies]
scoped_threadpool = "0.1.*"
stats_alloc = "0.1.*"
